### ISSUE TITLE
NoClassDefFoundError Crash: "Failed resolution of: Ljava/util/SequencedCollection" on initFpjs call

### ISSUE THREAD

**Issue by vitalii-petrun** [fingerprintjs/fingerprintjs-pro-flutter#95]
### Description

After upgrading package version from 2.1.1 to 4.0.0 'Failed resolution of: Ljava/util/SequencedCollection;' app crash appears on FpjsProPlugin.initFpjs call. 

### Environment

Library version: 4.0.0
Test Devices: physical phones with Android version 11 and 12.

### The full stacktrace of error:
```
Fatal Exception: java.lang.NoClassDefFoundError
Failed resolution of: Ljava/util/SequencedCollection;

com.fingerprintjs.android.fpjs_pro.Configuration.<init> (SourceFile:12)
com.fingerprintjs.flutter.fpjs_pro.fpjs_pro_plugin.FpjsProPlugin.initFpjs (FpjsProPlugin.kt:103)
com.fingerprintjs.flutter.fpjs_pro.fpjs_pro_plugin.FpjsProPlugin.onMethodCall (FpjsProPlugin.kt:68)
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage (MethodChannel.java:267)
io.flutter.embedding.engine.dart.DartMessenger.invokeHandler (DartMessenger.java:292)
io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0 (DartMessenger.java:319)
android.os.Handler.handleCallback (Handler.java:938)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:223)
android.app.ActivityThread.main (ActivityThread.java:7665)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:594)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:947)
```
### flutter doctor -v
```
[√] Flutter (Channel stable, 3.29.2, on Microsoft Windows [Version 10.0.26100.3775], locale en-US) [401ms]
    • Flutter version 3.29.2 on channel stable at C:\Users\vitalii\fvm\versions\3.29.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c236373904 (9 weeks ago), 2025-03-13 16:17:06 -0400
    • Engine revision 18b71d647a
    • Dart version 3.7.2
    • DevTools version 2.42.3

[√] Windows Version (11 Pro 64-bit, 24H2, 2009) [4.0s]

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [2.3s]
    • Android SDK at E:\SDKs\android
    • Platform android-35, build-tools 35.0.0
    • Java binary at: E:\Apps\AndroidStudio\jbr\bin\java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[√] Chrome - develop for the web [95ms]
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.2) [94ms]
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.11.35222.181
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2024.1) [16ms]
    • Android Studio at E:\Apps\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[√] Connected device (4 available) [481ms]
    • Redmi Note 7 (mobile) • b161c48 • android-arm64  • Android 11 (API 30)
    • Windows (desktop)     • windows • windows-x64    • Microsoft Windows [Version 10.0.26100.3775]
    • Chrome (web)          • chrome  • web-javascript • Google Chrome 136.0.7103.93
    • Edge (web)            • edge    • web-javascript • Microsoft Edge 136.0.3240.64

[√] Network resources [980ms]
    • All expected network resources are available.

• No issues found!
```
### android/app/build.gradle
```
plugins {
    id "com.android.application"
    // START: FlutterFire Configuration
    id 'com.google.gms.google-services'
    id 'com.google.firebase.crashlytics'
    // END: FlutterFire Configuration
    id "kotlin-android"
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id "dev.flutter.flutter-gradle-plugin"
}

dependencies {
}

android {
    namespace = "***"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId = "***"
        // You can update the following values to match your application needs.
        // For more information, see: https://flutter.dev/to/review-gradle-config.
        minSdk = 28
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig = signingConfigs.debug
        }
    }
}

flutter {
    source = "../.."
}
```

**Comment by vitalii-petrun** [comment]
Fixed this one

1. Updated version of id `"com.android.application" version "8.7.0" apply false` (was 8.1.0) in settings.gradle
2. Updated android block under android/app/build.gradle
```
ndkVersion = "27.0.12077973"

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11.toString()
    }
```
3. updated gradle-wrapper.properties 
`distributionUrl=https\://services.gradle.org/distributions/gradle-8.10.2-all.zip` was 8.8

**Comment by ilfa** [comment]
Hey @vitalii-petrun!

I am happy that you figured out.
Please, let us know if you need any additional help with our products.
